# Generated by Django 3.2.9 on 2021-11-15 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211115_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Наименование должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='chief',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='catalog.chief', verbose_name='Начальник'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='catalog.level', verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.position', verbose_name='Должность'),
        ),
    ]
